name: Deploy to Cloud Run

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  SERVICE_NAME: custom-fastapi-service
  PROJECT_ID: long-arcadia-475313-s8
  # We wonâ€™t hard-code PROJECT_ID here; instead we reference the variable
  # GOOGLE_CLOUD_PROJECT in the deployment step.
  DOCKER_IMAGE_URL: us-central1-docker.pkg.dev/long-arcadia-475313-s8/custom-fastapi/custom-fastapi

jobs:
  dockerize-and-deploy:
    runs-on: ubuntu-latest
    environment: GOOGLE_CLOUD_PROJECT
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Google Cloud Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ vars.GOOGLE_CLOUD_PROJECT }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ env.DOCKER_IMAGE_URL }}:latest -f Dockerfile .
          docker push ${{ env.DOCKER_IMAGE_URL }}:latest

      - name: Deploy to Cloud Run
        run: |
          echo SERVICE_NAME ${{ env.SERVICE_NAME }}
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image ${{ env.DOCKER_IMAGE_URL }}:latest \
            --platform managed \
            --region ${{ vars.GOOGLE_CLOUD_LOCATION }} \
            --allow-unauthenticated \
            --set-env-vars=GOOGLE_CLOUD_PROJECT=${{ vars.GOOGLE_CLOUD_PROJECT }},\
              GOOGLE_CLOUD_LOCATION=${{ vars.GOOGLE_CLOUD_LOCATION }},\
              SYSTEM_PROMPT="${{ vars.SYSTEM_PROMPT }}",\
              CACHE_TTL_SECONDS=${{ vars.CACHE_TTL_SECONDS }},\
              MAX_HISTORY_LENGTH=${{ vars.MAX_HISTORY_LENGTH }}